# Database Configuration (Supabase)
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.yqykxjkpetxfapkxjgtt
spring.datasource.password=6,DQr9euY&qiviF
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
pat.app.jwtSecret=PLACEMENT_COMPASS_VERY_SECRET_KEY_FOR_LOCAL_DEMO_SHOULD_BE_LONG_ENOUGH_FOR_HS256
pat.app.jwtExpirationMs=86400000

# OTP Configuration
pat.app.otpExpirationMs=300000

# Server Configuration
server.port=8080
logging.level.com.pat=DEBUG

# Email Configuration (SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=adithihebbar70@gmail.com
spring.mail.password=hlqd wopn nwqf zfuc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
